version: '{build}'

image:
  - Visual Studio 2017
  
environment:
  project_name: reed-solomon
  project_tests_name: reed-solomon.test

platform:
  - x86

configuration:
  - Release

install:
  - git submodule update --init --recursive
  
before_build:
- cd src\%project_name%\
- nuget restore
- cd ..\..

build:
  project: src\%project_name%\%project_name%.sln
  
test_script:
  - vstest.console /logger:Appveyor src\%project_name%\%CONFIGURATION%\%project_tests_name%.dll

artifacts:
  - path: 'src\%project_name%\%CONFIGURATION%\%project_name%.dll'
  - path: 'src\%project_name%\%CONFIGURATION%\%project_tests_name%.dll'
