version: '{build}'

image:
  - Visual Studio 2017
  
environment:
  project_name: reed-solomon

configuration:
  - Release

install:
  - git submodule update --init --recursive

build:
  project: src\%project_name%\%project_name%.sln

artifacts:
  - path: 'src\%project_name%\%CONFIGURATION%\%project_name%.dll'
